//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestingGrid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestClassEntry
    {
        public int id { get; set; }
        public Nullable<int> SL { get; set; }
        public string Name { get; set; }
        public string Roll { get; set; }
        public string Class { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
    }
}
